apiVersion: apps/v1
kind: Deployment
metadata:
  name: haystack-rag-api
  labels:
    app: haystack-rag-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: haystack-rag-api
  template:
    metadata:
      labels:
        app: haystack-rag-api
    spec:
      containers:
        - name: haystack-rag-api
          image: haystack-rag-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
